# Generated by Django 4.2.30 on 2026-07-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('event_date', models.DateField(blank=True, help_text='Requested performance date', null=True)),
                ('event_type', models.CharField(choices=[('club', 'Club / venue'), ('private', 'Private event'), ('wedding', 'Wedding'), ('corporate', 'Corporate event'), ('festival', 'Festival'), ('other', 'Other')], default='private', max_length=20)),
                ('venue', models.CharField(blank=True, help_text='Venue name and city', max_length=255)),
            ],
            options={
                'verbose_name': 'Booking Inquiry',
                'verbose_name_plural': 'Booking Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
