# Generated by Django 4.2.30 on 2026-07-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='calendar_embed_code',
            field=models.TextField(blank=True, help_text="Optional: paste Google Calendar's full <iframe> embed code (Settings and sharing → Integrate calendar → Embed code) for full control over size and view — used instead of the URL above when set."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='calendar_url',
            field=models.URLField(blank=True, help_text="Google Calendar's own “Public URL to this calendar” (Settings and sharing → Integrate calendar), or just the calendar ID (name@group.calendar.google.com) — either works. Ignored if an embed code is set below."),
        ),
    ]
