# Generated by Django 4.2.30 on 2026-08-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_calendar_embed_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='calendar_embed_code',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='map_embed_url',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='calendar_url',
            field=models.URLField(blank=True, help_text="Google Calendar's own “Public URL to this calendar” (Settings and sharing → Integrate calendar), or just the calendar ID (name@group.calendar.google.com) — either works."),
        ),
    ]
