# Generated by Django 4.2.30 on 2026-08-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sitesettings_calendar_embed_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedBrand',
        ),
        migrations.DeleteModel(
            name='HomeSectionCard',
        ),
    ]
