# Generated by Django 4.2.30 on 2026-08-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Move this post out of the main Blog feed into the Archive list at the bottom of the page — still published and linkable, just out of the way.'),
        ),
    ]
