# Generated by Django 4.2.30 on 2026-07-27 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='team.teammember')),
            ],
            options={
                'verbose_name': 'Member Photo',
                'verbose_name_plural': 'Member Photos',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
