# Generated by Django 4.2.30 on 2026-07-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioEmbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_url', models.URLField(blank=True, help_text='Spotify or SoundCloud link — the player is generated automatically')),
                ('embed_code', models.TextField(blank=True, help_text='Bandcamp (or other) embed iframe — used when a plain link is not enough')),
                ('caption', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Audio Embed',
                'verbose_name_plural': 'Audio Embeds',
                'ordering': ['sort_order'],
            },
        ),
    ]
