# Generated by Django 4.2.30 on 2026-08-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_audioembed'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Shown in the home page\'s "See us in action" section. Only one photo should be featured at a time — the most recently marked one wins if more than one is checked.'),
        ),
    ]
