# Generated by Django 4.2.30 on 2026-08-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_galleryphoto_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryvideo',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Shown in the home page\'s "See Us in Action" section — the first one checked (by sort order) wins, since that section shows one video.'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Shown in the home page\'s "See Us in Action" section. Check as many as you like.'),
        ),
    ]
