# Generated by Django 4.2.30 on 2026-08-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_galleryvideo_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='is_hero',
            field=models.BooleanField(default=False, help_text="Use as the home page's main hero photo (desktop). Check one — the first by sort order wins."),
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='is_hero_mobile',
            field=models.BooleanField(default=False, help_text="Use as the home page's hero photo on phones. Check one — the first by sort order wins. Falls back to the desktop hero pick if none is checked."),
        ),
    ]
